### ISSUE TITLE
Missing support for "ui" pinyin constituent?

### ISSUE THREAD

**Issue by davidavdav** [issiki/pinyin-tone#2]
**Describe the bug**

```js
pytone('dui4') === 'dui4'
```
I would expect duì, and similarly for other tones

**To Reproduce**

```js
> var pytone = require('pinyin-tone');
> for (i=0; i<5; i++) { console.log(pytone('dui' + i)); }
dui0
dui1
dui2
dui3
dui4
```

**Expected behavior**

```js
var pytone = require('pinyin-tone');
> for (i=0; i<5; i++) { console.log(pytone('dui' + i)); }
dui
duī
duí
duǐ
duì
```

**Desktop (please complete the following information):**
 - OS: unix
 - Browser: node
 - Version: v12.16.3

**Additional context**

**Comment by issiki** [comment]
Hi, @davidavdav 
Thank you for your feedback.

I just rewrote the code, fixed that bug and did some tests.
