### ISSUE TITLE
Can we add support for tone mark 5?

### ISSUE THREAD

**Issue by OultimoCoder** [issiki/pinyin-tone#5]
I know tone mark 5 is essentially no tone e.g. 书呆子 == shū dāi zi but popular free dictionaries like ccedict explicitly mark tone 5 so it would display 书呆子 == shū dāi zi5 if it was converted using pinyin-tone. It would be nice to have support for this and just remove the 5.

Thanks!

**Comment by issiki** [comment]
In modern Mandarin/Chinese, 轻声 is not the 5th tone, but a special variation of the four tones.

I am curious about their reason for marking 轻声 as 5.

**Comment by OultimoCoder** [comment]
Hi! It wasn't me who marked it like this, I am referencing CC-EDICT a popular Chinese to English dictionary. They mark it this way.

https://www.mdbg.net/chinese/dictionary?page=cedict

**Comment by issiki** [comment]
Tone mark 5 is now supported.

> 
> 
> Hi! It wasn't me who marked it like this, I am referencing CC-EDICT a popular Chinese to English dictionary. They mark it this way. Unfortunately, I can't answer why they have done this but for English people learning Chinese it is sometimes marked this way (most of the time just left blank). Maybe it could be configurable?
> 
> https://www.mdbg.net/chinese/dictionary?page=cedict



> 
> 
> I'd like to see this, too 🙂
> 
> I use the 5th tone for some courses on my website (http://mylittlewordland.com), and [www.memrise.com](http://www.memrise.com) uses it for some of its Chinese courses, too 🙂 I think the idea is that having the 5 makes it clear that the character doesn't have a tone. Without the 5, it's possible that the missing tone is just a typo 🙂

**Comment by neoncube2** [comment]
Yay! Thank you! 🙂
